# Infrastructure Diagram — Task Manager SDD
# Generated by solution-designer · 2026-07-08
# Run: python docs/diagrams/infrastructure.py
#
# Quality settings: 300 DPI, ortho splines, Sans-Serif fonts
# Styling based on SDD infra-diagram-template.py constants

from diagrams import Diagram, Cluster, Edge
from diagrams.aws.database import RDS
from diagrams.aws.security import IAM
from diagrams.aws.management import Cloudwatch
from diagrams.onprem.client import Users
from diagrams.onprem.container import Docker
from diagrams.programming.framework import React
from diagrams.programming.language import NodeJS
from diagrams.onprem.security import Vault
from diagrams.generic.network import Firewall
from diagrams.saas.cdn import Cloudflare

# ─── HD Graph Attributes ─────────────────────────────────
GRAPH_ATTR = {
    "bgcolor": "#ffffff",
    "pad": "2.0",
    "fontsize": "16",
    "fontname": "Sans-Serif",
    "fontcolor": "#1a1a2e",
    "splines": "ortho",
    "nodesep": "0.80",
    "ranksep": "0.90",
    "dpi": "600",
}

NODE_ATTR = {
    "fontname": "Sans-Serif",
    "fontsize": "12",
    "fontcolor": "#2D3436",
}

# ─── Cluster Styles (from SDD template) ──────────────────
CLUSTER_VERCEL = {
    "bgcolor": "#f0f7ff",
    "style": "rounded",
    "pencolor": "#0070f3",
    "penwidth": "2.0",
    "fontname": "Sans-Serif",
    "fontsize": "14",
    "fontcolor": "#0050b3",
}

CLUSTER_AWS = {
    "bgcolor": "#fff8f0",
    "style": "rounded",
    "pencolor": "#ff9900",
    "penwidth": "2.0",
    "fontname": "Sans-Serif",
    "fontsize": "14",
    "fontcolor": "#cc7a00",
}

CLUSTER_SECURITY = {
    "bgcolor": "#fffbf0",
    "style": "rounded",
    "pencolor": "#d4a017",
    "penwidth": "1.5",
    "fontname": "Sans-Serif",
    "fontsize": "12",
    "fontcolor": "#8a6d00",
}

CLUSTER_INNER = {
    "bgcolor": "#ffffff",
    "style": "rounded",
    "pencolor": "#d0d7de",
    "penwidth": "1.5",
    "fontname": "Sans-Serif",
    "fontsize": "11",
    "fontcolor": "#57606a",
}

CLUSTER_LOCAL = {
    "bgcolor": "#f0fff4",
    "style": "rounded",
    "pencolor": "#2da44e",
    "penwidth": "2.0",
    "fontname": "Sans-Serif",
    "fontsize": "14",
    "fontcolor": "#1a7f37",
}


# ─── Production ───────────────────────────────────────────
with Diagram(
    "",
    filename="docs/diagrams/infrastructure",
    show=False,
    direction="LR",
    graph_attr=GRAPH_ATTR,
    node_attr=NODE_ATTR,
):
    users = Users("Clients")

    with Cluster("VERCEL PLATFORM", graph_attr=CLUSTER_VERCEL):
        with Cluster("Edge CDN", graph_attr=CLUSTER_INNER):
            cdn = Cloudflare("SSL/TLS\nGlobal CDN")

        with Cluster("Frontend SPA", graph_attr=CLUSTER_INNER):
            spa = React("React 18\nVite + TypeScript")

        with Cluster("Security Layer", graph_attr=CLUSTER_SECURITY):
            api_gate = Firewall("API Key Gate\nx-api-key header")
            jwt = Vault("JWT Verify\nToken → userId")

        with Cluster("Business Logic", graph_attr=CLUSTER_INNER):
            api = NodeJS("Express 5\nControllers + Prisma")

    with Cluster("AWS  ·  us-east-1", graph_attr=CLUSTER_AWS):
        with Cluster("VPC  ·  Private Subnet", graph_attr=CLUSTER_INNER):
            db = RDS("PostgreSQL 16\ndb.t3.micro · 20GB\n~$15/mo")

        iam = IAM("IAM Role\nDB Credentials")
        monitoring = Cloudwatch("CloudWatch\nAlarms + Logs")

    # Client → Vercel
    users >> Edge(color="#0070f3", style="bold", label="HTTPS") >> cdn
    cdn >> Edge(color="#0070f3") >> spa

    # Frontend → Security → API
    spa >> Edge(color="#666666", label="fetch /api/*") >> api_gate
    api_gate >> Edge(color="#d4a017", style="bold", label="✓ valid key") >> jwt
    jwt >> Edge(color="#d4a017", style="bold", label="✓ userId") >> api

    # API → AWS
    api >> Edge(color="#7c3aed", style="bold", label="Prisma ORM\nTCP :5432") >> db

    # AWS internal
    iam >> Edge(style="dashed", color="#999999", label="rotate\ncredentials") >> db
    db >> Edge(style="dashed", color="#999999", label="metrics") >> monitoring


# ─── Development ──────────────────────────────────────────
with Diagram(
    "",
    filename="docs/diagrams/infrastructure-dev",
    show=False,
    direction="LR",
    graph_attr=GRAPH_ATTR,
    node_attr=NODE_ATTR,
):
    dev = Users("Developer")

    with Cluster("LOCAL  ·  localhost", graph_attr=CLUSTER_LOCAL):
        with Cluster("Frontend  :3000", graph_attr=CLUSTER_INNER):
            vite = React("Vite Dev Server\nHMR + Proxy")

        with Cluster("API  :4000", graph_attr=CLUSTER_INNER):
            express = NodeJS("Express 5\nnodemon + ts-node")

        with Cluster("Docker  :5432", graph_attr=CLUSTER_INNER):
            pg = Docker("postgres:16-alpine\nVolume persistente")

    dev >> Edge(color="#2da44e", style="bold", label="http://localhost:3000") >> vite
    vite >> Edge(color="#666666", label="proxy /api → :4000") >> express
    express >> Edge(color="#7c3aed", style="bold", label="DATABASE_URL") >> pg
